name: dashly
services:
  app:
    image: lklynet/dashly:latest
    container_name: dashly
    hostname: ${BASE_HOST_NAME:-dashly}
    restart: always
    pull_policy: always
    environment:
      - NGINX_DB_PATH=/nginx/dashly.sqlite
    ports:
      - '127.0.0.1:60189:8080'
    volumes:
      - '/var/lib/srv/$USER/docker/lklynet/dashly/latest/rootfs/data/dashly:/data'
      - '/var/lib/srv/$USER/docker/lklynet/dashly/latest/rootfs/data/db/nginx/dashly.sqlite:/nginx/dashly.sqlite'
